# Generated by Django 2.1.2 on 2018-10-26 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tcollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tcommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.TextField()),
                ('time', models.DateTimeField(max_length=20)),
                ('field01', models.CharField(max_length=200, null=True)),
                ('field02', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentt', models.TextField(default='not have message')),
            ],
        ),
        migrations.CreateModel(
            name='tcover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='timages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='travelnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField(max_length=20)),
                ('good', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=200)),
                ('content', models.TextField(default='聪明人才能看见的简介')),
                ('file1', models.CharField(max_length=200, null=True)),
                ('file2', models.CharField(max_length=200, null=True)),
                ('condition', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelnote.condition')),
                ('contentall', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelnote.tcontent')),
                ('cover', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelnote.tcover')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='timages',
            name='timages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelnote.travelnote'),
        ),
        migrations.AddField(
            model_name='tcommit',
            name='tid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelnote.travelnote'),
        ),
        migrations.AddField(
            model_name='tcommit',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='tcollection',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelnote.travelnote'),
        ),
        migrations.AddField(
            model_name='tcollection',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
